version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - product_db
    volumes:
      - .:/src
  product_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${database_name}
      - POSTGRES_USER=${database_user}
      - POSTGRES_PASSWORD=${database_sit_password}
